'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { FaHeart, FaVideo, FaChartLine } from 'react-icons/fa';

const quotes = [
  {
    text: "Your mental health is a priority. Your happiness is essential. Your self-care is a necessity.",
    author: "Unknown",
  },
  {
    text: "Healing takes time, and asking for help is a courageous step.",
    author: "Unknown",
  },
  {
    text: "You are stronger than you think, more capable than you imagine, and more loved than you know.",
    author: "Unknown",
  },
];

export default function Home() {
  return (
    <div className="space-y-16">
      {/* Hero Section */}
      <section className="text-center py-20">
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-4xl md:text-6xl font-bold text-purple-600 mb-6"
        >
          Welcome to InnerHarmony
        </motion.h1>
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="text-xl text-gray-600 max-w-2xl mx-auto mb-8"
        >
          A safe space for women to nurture their mental well-being through therapy,
          AI counseling, and mood tracking.
        </motion.p>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="flex flex-col sm:flex-row gap-4 justify-center"
        >
          <Link
            href="/therapy"
            className="bg-purple-600 text-white px-6 py-3 rounded-lg hover:bg-purple-700 transition-colors"
          >
            Start Therapy
          </Link>
          <Link
            href="/generate"
            className="bg-pink-500 text-white px-6 py-3 rounded-lg hover:bg-pink-600 transition-colors"
          >
            Generate AI Counseling
          </Link>
        </motion.div>
      </section>

      {/* Features Section */}
      <section className="grid md:grid-cols-3 gap-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="bg-white p-6 rounded-xl shadow-sm"
        >
          <FaHeart className="text-4xl text-pink-500 mb-4" />
          <h3 className="text-xl font-semibold mb-2">Therapy Sessions</h3>
          <p className="text-gray-600">
            Access professional therapy sessions tailored for women's mental health needs.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="bg-white p-6 rounded-xl shadow-sm"
        >
          <FaVideo className="text-4xl text-purple-500 mb-4" />
          <h3 className="text-xl font-semibold mb-2">AI Counseling</h3>
          <p className="text-gray-600">
            Get personalized counseling videos generated by AI based on your concerns.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="bg-white p-6 rounded-xl shadow-sm"
        >
          <FaChartLine className="text-4xl text-blue-500 mb-4" />
          <h3 className="text-xl font-semibold mb-2">Mood Tracking</h3>
          <p className="text-gray-600">
            Track your emotional well-being and get insights into your mental health journey.
          </p>
        </motion.div>
      </section>

      {/* Inspirational Quotes */}
      <section className="py-12">
        <h2 className="text-2xl font-bold text-center mb-8">Words of Wisdom</h2>
        <div className="grid md:grid-cols-3 gap-6">
          {quotes.map((quote, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.2 }}
              className="bg-white p-6 rounded-xl shadow-sm"
            >
              <p className="text-gray-600 italic mb-4">"{quote.text}"</p>
              <p className="text-gray-500 text-right">- {quote.author}</p>
            </motion.div>
          ))}
        </div>
      </section>
    </div>
  );
} 